export const APP_VERSION = '2.0.0';

export const CHANGE_LOGIN = 'CHANGE_LOGIN';
export const DO_LOGOUT = 'DO_LOGOUT';
export const PREPARE_FETCH_SOLICITACAO = 'PREPARE_FETCH_SOLICITACAO';
export const GOT_FETCH_SOLICITACAO = 'GOT_FETCH_SOLICITACAO';
export const ERROR_FETCH_SOLICITACAO = 'ERROR_FETCH_SOLICITACAO';
export const SHOW_MENU = 'SHOW_MENU';
export const HIDE_MENU = 'HIDE_MENU';
export const CHANGE_TEXT_VALUE = 'CHANGE_TEXT_VALUE';

