export const APP_VERSION = '2.0.0';

export const CHANGE_LOGIN = 'CHANGE_LOGIN';
export const DO_LOGOUT = 'DO_LOGOUT';
export const PREPARE_FETCH_SOLICITACAO = 'PREPARE_FETCH_SOLICITACAO';
export const GOT_FETCH_SOLICITACAO = 'GOT_FETCH_SOLICITACAO';
export const ERROR_FETCH_SOLICITACAO = 'ERROR_FETCH_SOLICITACAO';
